services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:6969

  nginx:
    depends_on:
      - backend
    image: nginx:1.27.3
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro